"""panel_expansion_select.py — apply the PRE-REGISTERED selection rule (S1-S3) to the
OpenAQ census, producing the non-Chinese panel shortlist.

Criteria + selection rule are fixed in docs/panel_expansion_eligibility_2026-07-26.md
BEFORE any city is scored. Nothing here touches a model. Selection is on data quality
and country diversity only.

In : data/processed/cnemc_panel/openaq_census/clusters_prescreen.csv  (post E1/E3)
Out: data/processed/cnemc_panel/panel_expansion_shortlist.csv
     docs/panel_expansion_candidates_summary.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
CENSUS = REPO / "data" / "processed" / "cnemc_panel" / "openaq_census"
OUT = REPO / "data" / "processed" / "cnemc_panel" / "panel_expansion_shortlist.csv"
SUMMARY = REPO / "docs" / "panel_expansion_candidates_summary.md"

PER_COUNTRY_CAP = 3          # S1
TARGET = 40                  # S3
MAX_EXTENT_KM = 50.0         # E8 (Amendment 1) — cluster must be city-scale, not a region


def main() -> int:
    c = pd.read_csv(CENSUS / "clusters_prescreen.csv")
    n_raw = len(c)
    c = c[c.iso != "CN"].copy()          # China already in the panel in full
    n_nonchina = len(c)

    # ---- E8 (Amendment 1): bound cluster spatial extent BEFORE ranking ----
    # Ranking on station count rewards large clusters, so extent must be capped first,
    # otherwise `max_concurrent` proxies for area rather than network density.
    import numpy as np
    lc = pd.read_csv(CENSUS / "locations_clustered.csv")
    ext = lc.groupby("cluster").agg(la=("lat", "min"), lb=("lat", "max"),
                                    oa=("lon", "min"), ob=("lon", "max"))
    ns = (ext.lb - ext.la) * 111.0
    ew = (ext.ob - ext.oa) * 111.0 * np.cos(np.radians((ext.lb + ext.la) / 2))
    ext["extent_km"] = pd.concat([ns, ew], axis=1).max(axis=1)

    # ---- E3-on-reference (Amendment 2): count only reference-grade monitors, and do it
    # HERE, before ranking, so E3 and E6 are consistent and station count cannot be
    # inflated by uncalibrated low-cost sensors.
    ref = lc[lc.is_monitor == True].groupby("cluster").size().rename("n_ref")  # noqa: E712
    ext = ext.join(ref).fillna({"n_ref": 0})
    c = c.merge(ext[["extent_km", "n_ref"]].reset_index(), on="cluster", how="left")
    n_pre_ref = len(c)
    c = c[c.n_ref >= 3].copy()
    print(f"E3-on-reference (>=3 ref monitors): {n_pre_ref} -> {len(c)}")
    n_pre_e8 = len(c)
    c = c[c.extent_km <= MAX_EXTENT_KM].copy()
    print(f"E8 (extent <= {MAX_EXTENT_KM:.0f} km): {n_pre_e8} -> {len(c)} "
          f"({n_pre_e8 - len(c)} region-merges excluded)")

    # completeness proxy from metadata: we have span only, so record it as UNKNOWN
    # rather than inventing a number. E2/E4/E5/E6 are applied downstream on real data.
    if "completeness_pct" not in c.columns:
        c["completeness_pct"] = pd.NA

    # ---- S2: within-country data-quality rank (blind to model performance) ----
    c = c.sort_values(["iso", "n_ref", "win_days", "cluster"],
                      ascending=[True, False, False, True])
    c["rank_in_country"] = c.groupby("iso").cumcount() + 1

    # ---- S1: per-country cap ----
    capped = c[c.rank_in_country <= PER_COUNTRY_CAP].copy()

    # ---- S3: breadth-first fill to TARGET ----
    # take each country's #1 first, then #2s, then #3s -> maximises country count
    capped = capped.sort_values(["rank_in_country", "n_ref", "win_days", "cluster"],
                                ascending=[True, False, False, True])
    sel = capped.head(TARGET).copy()
    sel["selected"] = True

    sel = sel.sort_values(["iso", "rank_in_country"])
    sel.to_csv(OUT, index=False)

    # ---------------- report ----------------
    print(f"census clusters (all)          : {n_raw}")
    print(f"non-Chinese clusters           : {n_nonchina}")
    print(f"countries available            : {c.iso.nunique()}")
    print(f"after per-country cap of {PER_COUNTRY_CAP}     : {len(capped)}")
    print(f"SELECTED (target {TARGET})           : {len(sel)}")
    print(f"countries in selection         : {sel.iso.nunique()}")
    print(f"cities per country             : "
          f"{sel.iso.value_counts().value_counts().to_dict()}  (n_cities: n_countries)")
    print()
    print("selection by country:")
    for iso, g in sel.groupby("iso"):
        print(f"  {iso} {g.country.iloc[0][:26]:<26} n={len(g)}  "
              f"stations {list(g.max_concurrent)}  span_days {list(g.win_days)}")

    lines = [
        "# Panel expansion — candidate census and selection",
        "",
        f"Generated by `scripts/panel_expansion_select.py` under the pre-registered rule in",
        "`docs/panel_expansion_eligibility_2026-07-26.md`. **No model was run; selection is on",
        "data quality and country diversity only.**",
        "",
        "## Funnel",
        "",
        "| stage | count |",
        "|---|---|",
        f"| OpenAQ city clusters, all | {n_raw} |",
        f"| non-Chinese (China retained in full, separately) | {n_nonchina} |",
        f"| distinct countries available | {c.iso.nunique()} |",
        f"| after per-country cap of {PER_COUNTRY_CAP} (S1) | {len(capped)} |",
        f"| **selected (S3 target {TARGET})** | **{len(sel)}** |",
        f"| countries in selection | {sel.iso.nunique()} |",
        "",
        "E1 (>=2 yr span) and E3 (>=3 concurrent stations) were applied at the census stage.",
        "**E2 (completeness), E4 (magnitude sanity), E5 (QC), E6 (sensor grade) remain PENDING** —",
        "they require the actual PM2.5 records, not metadata, and are applied after ingest.",
        "Cities failing them are dropped and the shortfall reported rather than back-filled by",
        "relaxing a threshold.",
        "",
        "## Selection by country",
        "",
        "| ISO | country | cities | max concurrent stations | span (days) |",
        "|---|---|---|---|---|",
    ]
    for iso, g in sel.groupby("iso"):
        lines.append(f"| {iso} | {g.country.iloc[0]} | {len(g)} | "
                     f"{', '.join(map(str, g.max_concurrent))} | "
                     f"{', '.join(map(str, g.win_days))} |")
    SUMMARY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwritten: {OUT}\n         {SUMMARY}")
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    raise SystemExit(main())
