"""build_supplement_tables.py -- generate Paper 1's supplementary tables from their sources.

Counts and verdicts are READ, never typed (gotcha #94):
  Table S1  registrations and prediction counts      <- #writing/registrations.json
  Table S2  spatial-curve predictions X1-X13         <- spatial_curve{,_full}/analysis{,_s70}/summary.json
The rule texts in S2 are quoted from the registrations (rqn4y Section 5; amendment 26hp8 Section 5).

Usage: python papers/paper1_information_budget/supplement/build_supplement_tables.py
Out:   papers/paper1_information_budget/ai_reference_draft/06_supplement/S1_registrations.md, S2_spatial_predictions.md
"""
import io
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "papers" / "paper1_information_budget" / "ai_reference_draft" / "06_supplement"
REG = ROOT / "#writing" / "registrations.json"
MOD = ROOT / "kandy_pm25" / "data" / "processed" / "modular"

USED_IN = {
    "nxqgb": "earlier Colombo test (superseded)", "g6hqb": "2.3", "bkpyr": "2.1.4", "kx23c": "not used in Paper 1",
    "2jyfg": "2.8", "ad3py": "not used in Paper 1 (campaign, not deployed)", "6udm3": "2.8", "z89kt": "2.9",
    "rqn4y": "2.7, 3.6", "26hp8": "2.7, 3.6", "4whsc": "2.7", "4qs9c": "2.7, 2.10", "ueyfr": "2.6, 3.1",
    "b379r": "2.12.1, 3.1.5", "jea58": "2.12.2, 3.1.6", "mhgna": "2.12.3, 3.1.7", "fu59b": "2.7.8, 3.6.3",
}

RULES = [
    ("X1", "E3 and E4 increase in median with k across the registered sizes, in the primary frame."),
    ("X2", "E3 or E5 reaches a crossover k× ≤ 35 in at least half of primary-frame cities."),
    ("X3", "E2 saturates at k* ≤ 12, at a level whose paired difference from E1 lies within the detection limit."),
    ("X4", "No estimator's median curve exceeds the city's within-cell ceiling by more than the detection limit."),
    ("X5", "At matched k, cLHS ordering does not beat random ordering by more than the detection limit."),
    ("X6", "For every estimator, the Q2 curve lies below the Q1 curve, and the ranking of estimators at the "
           "largest common k is the same in both."),
    ("X7", "The reach in the median primary-frame city is below 5 km."),
    ("X8", "(exploratory) In the band arm, every city's E3 curve lies inside the primary-frame envelope at every k."),
    ("X9", "No deep estimator (E8–E11) exceeds E5 by more than the detection limit at any registered k."),
    ("X10", "E9 beats E8 at every k ≥ 12 in the primary frame."),
    ("X11", "For E10 and for E11, the paired advantage over E3 at k = 3 and 5 exceeds the advantage at the two "
            "largest k the city allows, in the median primary city."),
    ("X12", "E10 and E11 differ by less than the detection limit at every registered k."),
    ("X13", "(exploratory) E10 and E11 on the band arm, against the primary-frame envelope."),
]


def word(v, deep_run=True):
    if isinstance(v, dict):
        v = v.get("holds", v)
    if isinstance(v, dict):                                        # X11 per estimator
        return "; ".join(f"{k} {'held' if x else 'refuted' if x is False else 'not testable'}" for k, x in v.items())
    if v is True:
        return "held"
    if v is False:
        return "refuted"
    return "not tested" if not deep_run else "not testable"


def s1() -> str:
    r = json.loads(REG.read_text(encoding="utf-8"))
    rows = r["registrations"]
    lines = ["[GENERATED by `supplement/build_supplement_tables.py` from `#writing/registrations.json`; do not edit.]", "",
             "**Table S1.** Every registration lodged on the Open Science Framework during the project, with its "
             "predictions and outcomes. *Held* means the registered expectation matched the outcome, including "
             "expectations of a null. Two-sided endpoints and exploratory analyses carry no direction and are counted "
             "separately.", "",
             "| OSF | registration | date | predictions | held | refuted | not tested | two-sided / exploratory | used in |",
             "|---|---|---|---|---|---|---|---|---|"]
    tot = dict(p=0, h=0, r=0, n=0, d=0)
    for x in rows:
        def g(k):
            v = x.get(k)
            return "" if v is None else str(v)
        lines.append(f"| {x['osf']} | {x['name']} | {x.get('date', '')} | {g('predictions')} | {g('held')} | "
                     f"{g('refuted')} | {g('not_tested')} | {g('descriptive')} | {USED_IN.get(x['osf'], '')} |")
        ran = x.get("kind") == "run" or str(x.get("status", "")).startswith("run")
        if ran:
            for k, c in (("p", "predictions"), ("h", "held"), ("r", "refuted"), ("n", "not_tested"), ("d", "descriptive")):
                tot[k] += int(x.get(c) or 0)
    nrun = sum(1 for x in rows if x.get("kind") == "run" or str(x.get("status", "")).startswith("run"))
    lines.append(f"| **total, {nrun} with outcomes** | | | **{tot['p']}** | **{tot['h']}** | **{tot['r']}** | "
                 f"**{tot['n']}** | **{tot['d']}** | |")
    t = r["_totals_over_analyses_that_have_run"]
    assert (tot["p"], tot["h"], tot["r"], tot["n"], tot["d"]) == (
        t["predictions"], t["held"], t["refuted"], t["not_tested"], t["descriptive"]), "registry totals disagree"
    return "\n".join(lines) + "\n"


def s2() -> str:
    runs = [("registered, 75 %", MOD / "spatial_curve/analysis/summary.json", True),
            ("registered, S-1 70 %", MOD / "spatial_curve/analysis_s70/summary.json", True),
            ("full records, 75 %", MOD / "spatial_curve_full/analysis/summary.json", False),
            ("full records, S-1 70 %", MOD / "spatial_curve_full/analysis_s70/summary.json", False)]
    V = [(n, json.loads(p.read_text(encoding="utf-8"))["verdicts"], deep) for n, p, deep in runs]
    lines = ["[GENERATED by `supplement/build_supplement_tables.py` from the summary files of OSF rqn4y/26hp8 and fu59b; "
             "do not edit.]", "",
             "**Table S2.** The spatial learning curve's registered predictions, their decision rules (quoted from the "
             "registrations) and their outcomes in each frame. The full-record extension did not re-run the deep arms, so "
             "X9 to X13 are *not tested* there. X12 could not be tested in the registered run because E11 failed its "
             "positive control. Exploratory predictions (X8, X13) are reported in Section 3.6.3 and are not scored here.", "",
             "| id | registered rule | " + " | ".join(n for n, _, _ in V) + " |",
             "|---|---|" + "---|" * len(V)]
    for xid, rule in RULES:
        key = xid if xid not in ("X8", "X13") else f"{xid}_exploratory"
        cells = []
        for _, v, deep in V:
            if xid in ("X8", "X13"):
                cells.append("exploratory")
            elif xid in ("X9", "X10", "X11", "X12") and not deep:
                cells.append("not tested")
            else:
                cells.append(word(v.get(key)))
        lines.append(f"| {xid} | {rule} | " + " | ".join(cells) + " |")
    lines += ["", "Detection limits at the number of primary countries: registered 0.28 (7 countries), full records 0.24 "
              "(9 countries). X6's second clause (the ranking of estimators at the largest common k) was not implemented in "
              "the scoring code; X6 is refuted on its first clause in every frame, so the omission cannot change its "
              "verdict (Section 2.10.2)."]
    return "\n".join(lines) + "\n"


def write(name, text):
    OUT.mkdir(parents=True, exist_ok=True)
    p = OUT / name
    tmp = p.with_suffix(".tmp")
    io.open(tmp, "w", encoding="utf-8").write(text)
    os.replace(tmp, p)
    print("wrote", p)


if __name__ == "__main__":
    write("S1_registrations.md", s1())
    write("S2_spatial_predictions.md", s2())
