"""
chiangmai_train_stage1.py — Train XGBoost Stage 1 model for Chiang Mai.

PURPOSE
-------
Mirrors the Medellín Stage 1 methodology but on Chiang Mai 2022 non-burning season.
Produces:
  (1) City-mean temporal predictions (BC for PINN)
  (2) Pixel-level predictions over CHIANGMAI_PINN_BBOX (PINN pseudo-labels)

PINN PSEUDO-LABELS DESIGN
--------------------------
The XGBoost is trained on city-mean temporal signal (Air4Thai 3-station average).
Pixel predictions are generated by replicating city-mean across the 150×150 grid,
with elevation-based scaling to introduce physically motivated spatial variation:

  C_pixel(x,y,t) = C_city(t) × elev_weight(x,y)

  elev_weight = exp( −λ × (elev(x,y) − elev_mean) / 1000 )
              where λ=0.20 (≈ 18% reduction per 1000m elevation gain)

Rationale: higher elevations have shallower valley influence; morning inversion
BLH is lower relative to ground → slightly lower PM2.5 than valley floor.
This provides the PINN a weak spatial gradient to start from; actual spatial
structure (3.55 µg/m³ inter-station std) is learned via PDE physics + road kernel.

NOTE: This is not a pixel model (no pixel-specific satellite features). The spatial
gradient is elevation-derived only. This exactly mirrors the Kandy workflow where
spatial structure comes from PINN physics, not Stage 1 XGBoost.

EXPECTED LOMO R²
----------------
~0.3–0.6 with 1-year data (vs Kandy's 0.631 with 23 years).
Low R² is expected and acceptable — purpose is BC generation, not temporal prediction.
(Medellín: 0.217 with CAMS-BC labels — we expect better here with real Air4Thai truth.)

Input:   data/processed/stage2/chiangmai_stage1_dataset.parquet
Output:  results/models/chiangmai_stage1_xgboost.ubj
         data/processed/stage2/chiangmai_stage1_predictions.parquet  (city-mean)
         data/processed/stage2/chiangmai_stage1_pixel_preds.npz     (150×150×n_days)
         results/tables/chiangmai_stage1_lomo_cv.csv

Usage:
    cd kandy_pm25/
    python src/stage2_transfer/chiangmai_train_stage1.py
    python src/stage2_transfer/chiangmai_train_stage1.py --tune       # Optuna tuning
    python src/stage2_transfer/chiangmai_train_stage1.py --no-shap    # skip SHAP
    python src/stage2_transfer/chiangmai_train_stage1.py --no-pixels  # skip pixel preds
"""

import argparse
import json
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score

sys.path.insert(0, str(Path(__file__).parents[2]))
from config import (
    PROC_DIR,
    MODELS_DIR,
    TABLES_DIR,
    FIGURES_DIR,
    PINN_INPUT_DIR,
    LOG_FORMAT, LOG_DATEFMT,
)

logging.basicConfig(format=LOG_FORMAT, datefmt=LOG_DATEFMT, level=logging.INFO)
log = logging.getLogger("chiangmai_train_stage1")

# ── Paths ─────────────────────────────────────────────────────────────────────
STAGE2_PROC_DIR   = PROC_DIR / "stage2"
DATASET_PARQUET   = STAGE2_PROC_DIR / "chiangmai_stage1_dataset.parquet"
PREDICTIONS_OUT   = STAGE2_PROC_DIR / "chiangmai_stage1_predictions.parquet"
PIXEL_PREDS_OUT   = STAGE2_PROC_DIR / "chiangmai_stage1_pixel_preds.npz"
MODEL_OUT         = MODELS_DIR / "chiangmai_stage1_xgboost.ubj"
CV_TABLE_OUT      = TABLES_DIR / "chiangmai_stage1_lomo_cv.csv"
OPTUNA_TRIALS_OUT = TABLES_DIR / "chiangmai_stage1_optuna_trials.csv"
BEST_PARAMS_OUT   = MODELS_DIR / "chiangmai_stage1_best_params.json"
SHAP_FIGURE_OUT   = FIGURES_DIR / "publication" / "chiangmai_stage1_shap.png"
ELEV_GRID_NPZ     = PINN_INPUT_DIR / "chiangmai_elev_grid_100m.npz"
KANDY_BEST_PARAMS = MODELS_DIR / "xgboost_best_params.json"

TARGET          = "pm25_observed"
RANDOM_SEED     = 42
NON_FEATURE_COLS = {TARGET, "month", "doy"}

# Elevation weighting decay constant for pixel predictions
# λ=0.20 → 18% reduction per 1000m gain (physically conservative estimate)
ELEV_WEIGHT_LAMBDA = 0.20

# Default params — start from Medellin tuned (closer to 1-year data regime than Kandy)
DEFAULT_PARAMS = {
    "n_estimators":      312,
    "learning_rate":     0.05,
    "max_depth":         5,
    "subsample":         0.8,
    "colsample_bytree":  0.8,
    "colsample_bylevel": 0.8,
    "min_child_weight":  3,
    "gamma":             0.5,
    "reg_alpha":         0.267,
    "reg_lambda":        1.0,
    "objective":         "reg:squarederror",
    "eval_metric":       "rmse",
    "n_jobs":            -1,
    "random_state":      RANDOM_SEED,
}


# ─────────────────────────────────────────────────────────────────────────────
def load_dataset() -> tuple[pd.DataFrame, list[str]]:
    """Load Chiang Mai Stage 1 dataset and determine feature columns."""
    if not DATASET_PARQUET.exists():
        raise FileNotFoundError(
            f"Dataset not found: {DATASET_PARQUET}\n"
            "Run chiangmai_build_dataset.py first."
        )
    df = pd.read_parquet(DATASET_PARQUET)
    log.info(f"Loaded: {df.shape[0]} rows × {df.shape[1]} cols")
    log.info(f"Date range: {df.index.min().date()} to {df.index.max().date()}")
    log.info(f"PM2.5: mean={df[TARGET].mean():.1f}, std={df[TARGET].std():.1f} µg/m³")

    features = [c for c in df.columns if c not in NON_FEATURE_COLS]
    valid_features = [f for f in features if df[f].notna().any()]
    dropped = set(features) - set(valid_features)
    if dropped:
        log.warning(f"Dropping all-NaN feature columns: {dropped}")
    log.info(f"Features ({len(valid_features)}): {sorted(valid_features)}")
    return df, valid_features


def compute_metrics(y_true, y_pred, label: str = "") -> dict:
    rmse = mean_squared_error(y_true, y_pred) ** 0.5
    r2   = r2_score(y_true, y_pred)
    mae  = float(np.abs(y_true - y_pred).mean())
    bias = float((y_pred - y_true).mean())
    if label:
        log.info(f"{label}: R²={r2:.3f}  RMSE={rmse:.2f}  MAE={mae:.2f}  Bias={bias:+.2f}")
    return {"r2": r2, "rmse": rmse, "mae": mae, "bias": bias}


# ─────────────────────────────────────────────────────────────────────────────
def run_lomo_cv(df: pd.DataFrame, features: list[str], params: dict) -> tuple:
    """
    Leave-One-Month-Out CV across 8 non-burning months (May–Dec 2022).
    With only 1 year of data, each fold has ~30 days held out, ~210 in training.
    """
    labelled = df[df[TARGET].notna()].copy()
    X, y     = labelled[features], labelled[TARGET]
    months   = labelled.index.month

    params_cv = {k: v for k, v in params.items() if k != "early_stopping_rounds"}
    fold_results = []
    all_preds    = pd.Series(dtype=float, index=labelled.index, name="pm25_pred_lomo")

    for month in sorted(months.unique()):
        test_mask = months == month
        X_tr, X_te = X[~test_mask], X[test_mask]
        y_tr, y_te = y[~test_mask], y[test_mask]

        if len(y_te) == 0:
            continue

        model = xgb.XGBRegressor(**params_cv)
        model.fit(X_tr, y_tr, verbose=False)
        pred = model.predict(X_te)
        all_preds[X_te.index] = pred

        m = compute_metrics(y_te.values, pred, label=f"LOMO Month {month:02d}")
        m["month"]  = month
        m["n_days"] = len(y_te)
        fold_results.append(m)

    cv_df = pd.DataFrame(fold_results)
    log.info("\n── LOMO Summary (Chiang Mai 2022 non-burning) ────────────────")
    for col in ["r2", "rmse", "mae", "bias"]:
        log.info(f"  {col:5s}: mean={cv_df[col].mean():.3f}  std={cv_df[col].std():.3f}")
    compute_metrics(y.values, all_preds.reindex(y.index).values, label="LOMO Overall")

    return cv_df, all_preds


# ─────────────────────────────────────────────────────────────────────────────
def tune_hyperparameters(df: pd.DataFrame, features: list[str], n_trials: int = 30) -> dict:
    """Optuna LOMO RMSE minimisation — 30 trials (small dataset, fast)."""
    try:
        import optuna
        optuna.logging.set_verbosity(optuna.logging.WARNING)
    except ImportError:
        log.warning("optuna not installed — using default params")
        return DEFAULT_PARAMS.copy()

    labelled = df[df[TARGET].notna()].copy()
    X, y     = labelled[features], labelled[TARGET]
    months   = labelled.index.month

    def objective(trial):
        p = {
            "n_estimators":      trial.suggest_int("n_estimators", 100, 1000),
            "learning_rate":     trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "max_depth":         trial.suggest_int("max_depth", 3, 8),
            "subsample":         trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree":  trial.suggest_float("colsample_bytree", 0.4, 1.0),
            "min_child_weight":  trial.suggest_int("min_child_weight", 1, 15),
            "gamma":             trial.suggest_float("gamma", 0.0, 3.0),
            "reg_alpha":         trial.suggest_float("reg_alpha", 1e-4, 20.0, log=True),
            "reg_lambda":        trial.suggest_float("reg_lambda", 1e-4, 20.0, log=True),
            "objective":         "reg:squarederror",
            "n_jobs":            -1,
            "random_state":      RANDOM_SEED,
        }
        fold_rmses = []
        for month in sorted(months.unique()):
            test_mask = months == month
            model = xgb.XGBRegressor(**p)
            model.fit(X[~test_mask], y[~test_mask], verbose=False)
            pred = model.predict(X[test_mask])
            fold_rmses.append(mean_squared_error(y[test_mask], pred) ** 0.5)
        return float(np.mean(fold_rmses))

    study = optuna.create_study(direction="minimize",
                                sampler=optuna.samplers.TPESampler(seed=RANDOM_SEED))
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

    best = study.best_params
    best.update({"objective": "reg:squarederror", "eval_metric": "rmse",
                 "n_jobs": -1, "random_state": RANDOM_SEED})
    log.info(f"Best LOMO RMSE: {study.best_value:.3f} µg/m³ (trial #{study.best_trial.number})")

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    with open(BEST_PARAMS_OUT, "w") as f:
        json.dump(best, f, indent=2)

    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    trials_df = study.trials_dataframe()
    trials_df.to_csv(OPTUNA_TRIALS_OUT, index=False)
    return best


# ─────────────────────────────────────────────────────────────────────────────
def generate_pixel_predictions(
    model: xgb.XGBRegressor,
    df: pd.DataFrame,
    features: list[str],
    city_preds: np.ndarray,
) -> np.ndarray:
    """
    Generate 150×150 pixel predictions for all training days.

    Uses elevation-based spatial weighting on top of city-mean predictions:
      C_pixel(x,y,t) = C_city(t) × elev_weight(x,y)
      elev_weight = exp(−λ × (elev(x,y) − elev_mean) / 1000)

    This gives valley floor higher PM2.5 than ridges — consistent with
    valley inversion dynamics and the 3.55 µg/m³ inter-station std observed.

    Returns: array of shape (n_days, 150, 150), float32.
    """
    if not ELEV_GRID_NPZ.exists():
        log.warning(f"Elevation grid not found: {ELEV_GRID_NPZ} — skipping pixel predictions")
        return None

    data = np.load(ELEV_GRID_NPZ)
    elev_grid = data["elev"].astype(np.float32)  # (150, 150), metres ASL
    H, W = elev_grid.shape

    elev_mean = float(np.nanmean(elev_grid))
    log.info(f"Elevation grid: {H}×{W}, mean={elev_mean:.0f}m, "
             f"range=[{elev_grid.min():.0f}, {elev_grid.max():.0f}]m")

    # Elevation weighting: valley floor (low elevation) → weight > 1, ridges → weight < 1
    # Normalise so that at the mean elevation weight = 1.0
    elev_weight = np.exp(-ELEV_WEIGHT_LAMBDA * (elev_grid - elev_mean) / 1000.0)
    log.info(f"Elevation weight range: [{elev_weight.min():.3f}, {elev_weight.max():.3f}]")

    n_days = len(city_preds)
    pixel_preds = np.zeros((n_days, H, W), dtype=np.float32)

    for i, c_city in enumerate(city_preds):
        # Broadcast city-mean × spatial elevation weight
        pixel_preds[i] = (c_city * elev_weight).astype(np.float32)

    log.info(f"Pixel predictions: shape={pixel_preds.shape}, "
             f"mean={pixel_preds.mean():.1f}, "
             f"spatial_std_mean={pixel_preds.std(axis=(1,2)).mean():.2f} µg/m³")
    return pixel_preds


def run_shap(model: xgb.XGBRegressor, X: pd.DataFrame) -> None:
    try:
        import shap
        import matplotlib.pyplot as plt
    except ImportError:
        log.warning("shap / matplotlib not installed — skipping SHAP")
        return

    log.info("Running SHAP analysis …")
    X_sample  = X.sample(min(200, len(X)), random_state=RANDOM_SEED)
    explainer = shap.TreeExplainer(model)
    sv        = explainer.shap_values(X_sample)

    importance = pd.DataFrame({
        "feature":       X.columns.tolist(),
        "mean_abs_shap": np.abs(sv).mean(axis=0),
    }).sort_values("mean_abs_shap", ascending=False)
    log.info("Top 15 features by mean |SHAP|:")
    log.info(importance.head(15).to_string(index=False))

    SHAP_FIGURE_OUT.parent.mkdir(parents=True, exist_ok=True)
    plt.figure(figsize=(10, 8))
    shap.summary_plot(sv, X_sample, show=False, max_display=20)
    plt.title("Chiang Mai Stage 1 — Feature Importance (SHAP)", fontsize=12)
    plt.tight_layout()
    plt.savefig(SHAP_FIGURE_OUT, dpi=150, bbox_inches="tight")
    plt.close()
    log.info(f"SHAP plot → {SHAP_FIGURE_OUT}")


# ─────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="Train Chiang Mai Stage 1 XGBoost (non-burning season 2022)"
    )
    parser.add_argument("--tune",       action="store_true", help="Run Optuna (30 trials)")
    parser.add_argument("--n-trials",   type=int, default=30, help="Optuna trial count")
    parser.add_argument("--no-shap",    action="store_true", help="Skip SHAP analysis")
    parser.add_argument("--no-pixels",  action="store_true", help="Skip pixel prediction generation")
    args = parser.parse_args()

    df, features = load_dataset()

    # ── Resolve hyperparameters ────────────────────────────────────────────────
    params = DEFAULT_PARAMS.copy()
    if BEST_PARAMS_OUT.exists() and not args.tune:
        with open(BEST_PARAMS_OUT) as f:
            params.update(json.load(f))
        log.info(f"Loaded tuned params from {BEST_PARAMS_OUT}")

    if args.tune:
        log.info(f"Running Optuna tuning ({args.n_trials} trials) …")
        params = tune_hyperparameters(df, features, n_trials=args.n_trials)

    # ── LOMO Cross-Validation ─────────────────────────────────────────────────
    log.info("\n── LOMO Cross-Validation ─────────────────────────────────────")
    cv_df, lomo_preds = run_lomo_cv(df, features, params)
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    cv_df.to_csv(CV_TABLE_OUT, index=False)
    log.info(f"CV table → {CV_TABLE_OUT}")

    # ── Train final model on full dataset ─────────────────────────────────────
    log.info("\n── Training final model on full dataset ─────────────────────")
    labelled = df[df[TARGET].notna()].copy()
    X_full, y_full = labelled[features], labelled[TARGET]
    final_params = {k: v for k, v in params.items() if k != "early_stopping_rounds"}
    model = xgb.XGBRegressor(**final_params)
    model.fit(X_full, y_full, verbose=False)
    train_pred = model.predict(X_full)
    compute_metrics(y_full.values, train_pred, label="Train-fit (in-sample)")

    # ── Save model ────────────────────────────────────────────────────────────
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    model.save_model(str(MODEL_OUT))
    log.info(f"Model → {MODEL_OUT}")

    # ── Save city-mean predictions ────────────────────────────────────────────
    preds_df = pd.DataFrame({
        "pm25_observed":  y_full,
        "pm25_pred":      train_pred,
        "pm25_pred_lomo": lomo_preds.reindex(y_full.index),
    }, index=y_full.index)
    STAGE2_PROC_DIR.mkdir(parents=True, exist_ok=True)
    preds_df.to_parquet(PREDICTIONS_OUT)
    log.info(f"City predictions → {PREDICTIONS_OUT}")

    # ── Pixel-level predictions (PINN pseudo-labels) ──────────────────────────
    if not args.no_pixels:
        log.info("\n── Generating pixel pseudo-labels (150×150) ─────────────────")
        pixel_preds = generate_pixel_predictions(model, df, features, train_pred)
        if pixel_preds is not None:
            # dates array for indexing
            dates = labelled.index.to_numpy(dtype="datetime64[D]")
            np.savez_compressed(
                PIXEL_PREDS_OUT,
                pixel_preds=pixel_preds,
                dates=dates,
            )
            log.info(f"Pixel predictions → {PIXEL_PREDS_OUT}  "
                     f"({PIXEL_PREDS_OUT.stat().st_size / 1e6:.1f} MB)")

    # ── SHAP ──────────────────────────────────────────────────────────────────
    if not args.no_shap:
        run_shap(model, X_full)

    log.info("\n── Done ─────────────────────────────────────────────────────")
    log.info(f"LOMO R²:   {cv_df['r2'].mean():.3f} ± {cv_df['r2'].std():.3f}")
    log.info(f"LOMO RMSE: {cv_df['rmse'].mean():.2f} ± {cv_df['rmse'].std():.2f} µg/m³")
    log.info(f"Model:     {MODEL_OUT}")

    # Gate check
    lomo_r2 = cv_df["r2"].mean()
    lomo_rmse = cv_df["rmse"].mean()
    log.info(f"\n── Gate check for Stage 1 ────────────────────────────────────")
    log.info(f"  LOMO R² = {lomo_r2:.3f}  (acceptable ≥ 0.20 for BC generation)")
    log.info(f"  LOMO RMSE = {lomo_rmse:.2f} µg/m³  (mean PM2.5 = {y_full.mean():.1f})")
    log.info(f"  {'PASS ✓' if lomo_r2 >= 0.20 else 'LOW — check features; proceed anyway (BC generation purpose)'}")


if __name__ == "__main__":
    main()
